# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{viddler}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Sabanin"]
  s.date = %q{2011-05-13}
  s.description = %q{Ruby wrapper around Viddler.com[http://www.viddler.com] API.

== FEATURES:

Currently implemented API methods:

* viddler.videos.getRecordToken
* viddler.users.register
* viddler.users.auth
* viddler.users.getProfile
* viddler.users.setProfile
* viddler.users.setOptions
* viddler.videos.upload
* viddler.videos.getStatus
* viddler.videos.getDetails
* viddler.videos.getDetailsByUrl
* viddler.videos.setDetails
* viddler.videos.getByUser
* viddler.videos.getByTag
* viddler.videos.getFeatured
}
  s.email = %q{ilya.sabanin@gmail.com}
  s.extra_rdoc_files = [
    "README.md",
    "README.txt"
  ]
  s.files = [
    ".bundle/config",
    ".rvmrc",
    "Gemfile",
    "History.txt",
    "License.txt",
    "README.md",
    "README.txt",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "lib/ext/array.rb",
    "lib/ext/hash.rb",
    "lib/ext/open_struct.rb",
    "lib/riddler.rb",
    "lib/riddler/client.rb",
    "lib/riddler/exceptions.rb",
    "lib/riddler/models/exceptions.rb",
    "lib/riddler/models/list.rb",
    "lib/riddler/models/playlist.rb",
    "lib/riddler/models/playlist_list.rb",
    "lib/riddler/models/regular_playlist.rb",
    "lib/riddler/models/session.rb",
    "lib/riddler/models/smart_playlist.rb",
    "lib/riddler/models/user.rb",
    "lib/riddler/models/video.rb",
    "lib/riddler/models/video_list.rb",
    "lib/viddler.rb",
    "lib/viddler/api_spec.rb",
    "lib/viddler/base.rb",
    "lib/viddler/comment.rb",
    "lib/viddler/multipart_params.rb",
    "lib/viddler/request.rb",
    "lib/viddler/user.rb",
    "lib/viddler/version.rb",
    "lib/viddler/video.rb",
    "spec/client_spec.rb",
    "spec/models/list_spec.rb",
    "spec/models/playlist_list_spec.rb",
    "spec/models/playlist_spec.rb",
    "spec/models/session_spec.rb",
    "spec/models/smart_playlist_spec.rb",
    "spec/models/user_spec.rb",
    "spec/models/video_list_spec.rb",
    "spec/models/video_spec.rb",
    "spec/spec_helper.rb",
    "test/fixtures/embed_code.txt",
    "test/test_helper.rb",
    "test/test_viddler.rb",
    "test/video.rb",
    "tmp/.gitignore",
    "viddler.gemspec"
  ]
  s.homepage = %q{http://viddler.rubyforge.org}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Ruby wrapper around Viddler.com API.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
  end
end

